<?php

namespace PS\PlaneBundle\Entity;

use Doctrine\ORM\EntityRepository;
use PS\PlaneBundle\Model\Location;

/**
 * AirportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirportRepository extends EntityRepository
{
    public function findOneByLocation(Location $location)
    {
        $query = $this->createQueryBuilder('a')
            ->where('a.locationX = :locationX')
            ->andWhere('a.locationY = :locationY')
            ->setParameters(array(
                'locationX' => $location->getX(),
                'locationY' => $location->getY()
            ))
            ->getQuery()
        ;

        try {
            return $query->getSingleResult();
        } catch(\Doctrine\ORM\NoResultException $e) {
            return null;
        }
    }
}
