<?php

namespace PS\PlaneBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlaneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaneRepository extends EntityRepository
{

}
